apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canasta.fullname" . }}-db
  labels:
    {{- include "canasta.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      {{- include "canasta.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: db
  template:
    metadata:
      labels:
        {{- include "canasta.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db
    spec:
      containers:
        - name: db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "canasta.fullname" . }}-env
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: "mediawiki"
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          volumeMounts:
        - name: initdb-volume
          mountPath: /docker-entrypoint-initdb.d
        - name: my-cnf-config
          mountPath: /etc/my.cnf
          subPath: my.cnf
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: initdb-volume
        {{- if eq .Values.persistence.type "hostPath" }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}/_initdb
          type: DirectoryOrCreate
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: my-cnf-config
        configMap:
          name: {{ include "canasta.fullname" . }}-config
          items:
            - key: "my.cnf"
              path: "my.cnf"
      - name: mysql-data
        persistentVolumeClaim:
          claimName: {{ include "canasta.fullname" . }}-mysql-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "canasta.fullname" . }}-db
  labels:
    {{- include "canasta.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "canasta.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
---
{{- if .Values.db.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "canasta.fullname" . }}-mysql-data
  labels:
    {{- include "canasta.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | quote }}
  {{- if .Values.db.persistence.storageClass }}
  storageClassName: {{ .Values.db.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
